markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name:  静中细思                                              # 博客名称
    description:                                         # 博客描述
    title:                                               # 网页标题
    url:                                                 # 博客地址
    duoshuo:                                             # 多说ID
    tongji:                                              # 百度统计ID
    qiniu:                                               # 七牛云地址
author:
    name:   kingnet                                             # 作者名称
    email:  jinguoxing_net@163.com                                             # 邮箱地址
    weibo:                                               # 微博地址
    github:  https://github.com/jinguoxing                                            # GitHub地址
    logo: https://avatars1.githubusercontent.com/u/2147893?v=3&s=460                                               # logo地址
